version: '3'
services: 
    influxdb:
        image: influxdb:latest
        ports: 
            - '8086:8086'
        volumes: 
            - influxdb-storage:/var/lib/influxdb
        environment: 
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
            - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORGANIZATION}
            - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}

    backend:
        container_name: backend
        depends_on:
            - influxdb
        environment:
            - INFLUXDB_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
            - INFLUXDB_ORGANIZATION=${INFLUXDB_ORGANIZATION}
            - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
            - INFLUXDB_URL=${INFLUXDB_URL}

        image: maven:3.6.3-jdk-11
        command: mvn spring-boot:run
        ports:
            - "8080:8080"
        volumes:
            - ./backend:/usr/src/mymaven:rw
        working_dir: /usr/src/mymaven

    frontend:
        image: "node:16-alpine"
        user: "node"
        working_dir: /app/frontend
        volumes: 
            - ./frontend:/app/frontend
        command: "yarn start"
        depends_on: 
            - backend
        ports: 
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true

        
volumes:
    influxdb-storage: