name: Backend workflow v1.0

on:
  push:
    branches: [ $default-branch ]

  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from Github
      uses: actions/checkout@v2
      
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml
